name: MX
version: '5.4 (Requin)'
api-version: '1.21.1'
author: pawsashatoy, Vagdedes, _The_Lord_, Loyisa, Dg32z, Bratif, ptrcall, yatwinkle, DanFM, Vladyaso, gamemax
description: "A fork of the original MX-Project for Packet Events"
main: kireiko.dev.anticheat.MX
depend: [packetevents ]
commands:
  mx:
    description: "Main command"
    usage: "/mx"
    permission: "mx.admin"
    aliases: [ mx ]
